spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:mysql://192.168.120.20:3306/mybatis_plus?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
          username: root
          password: z!cGnFq9YSvS$yop02*#pKUN5^ja$NpASIZjf&Vr
        slave_1:
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:mysql://192.168.120.20:3306/mybatis_plus_1?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
          username: root
          password: z!cGnFq9YSvS$yop02*#pKUN5^ja$NpASIZjf&Vr
mybatis-plus:
  configuration:
#    配置MP日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
#      设置实体类对应表的统一前缀
      table-prefix: t_
#      主键策略：默认UUID
      id-type: auto
#      配置类型别名所对应的包
  type-aliases-package: com.shf.mymp.pojo
#  扫描通用枚举的包
  type-enums-package: com.shf.mymp.enums